language: node_js
node_js:
- "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules


script:
- npm run build --base-href https://pandamorphism.github.io/fit-tracker-rx/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fit-tracker-rx
  on:
    branch: master
