language: node_js
node_js:
- "9"
dist: trusty
sudo: false

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - node_modules
install:
- npm install -g angular-cli-ghpages

script:
- npm run build-ghpages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist-ghpages
  on:
    branch: master
